name: Build & Release FDM AppImage

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git wget dpkg dpkg-dev imagemagick \
          sed coreutils file desktop-file-utils \
          binutils jq libfuse2

    - name: Download latest pkg2appimage
      run: |
        # Get the latest release information via GitHub API
        LATEST_URL=$(wget -qO- https://api.github.com/repos/AppImage/pkg2appimage/releases/latest | jq -r '.assets[] | select(.name | test("pkg2appimage-.*-x86_64.AppImage")) | .browser_download_url')
        echo "Downloading pkg2appimage from: $LATEST_URL"
        wget -c "$LATEST_URL" -O pkg2appimage.AppImage
        chmod +x pkg2appimage.AppImage

    - name: Build AppImage
      run: |
        ./pkg2appimage.AppImage recipes/freedownloadmanager.yml

    - name: Upload AppImage to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: out/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
